import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const template = path.resolve(
  __dirname,
  "../blank-paper-log.png"
);

function createEldPdf(trip, schedule) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margin: 0,
      autoFirstPage: false,
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("error", reject);

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    const pageW = 612;
    const pageH = 792;

    schedule.days.forEach((day) => {
      doc.addPage();

      doc.image(template, 0, 0, {
        width: pageW,
        height: pageH,
      });

      doc
        .fillColor("black")
        .font("Helvetica")
        .fontSize(7);

      const tx = (x) => (x * pageW) / 513;
      const ty = (y) => pageH - (y * pageH) / 518;

      doc.text(day.date, tx(177), ty(24));

      doc.text(
        String(trip.current_location).slice(0, 35),
        tx(66),
        ty(48)
      );

      doc.text(
        String(trip.dropoff_location).slice(0, 35),
        tx(286),
        ty(48)
      );

      doc.text(
        day.driving_hours.toFixed(1),
        tx(80),
        ty(108)
      );

      doc.text(
        day.on_duty_hours.toFixed(1),
        tx(170),
        ty(108)
      );

      const rows = {
        OFF_DUTY: 194,
        SLEEPER: 212,
        DRIVING: 230,
        ON_DUTY: 247,
      };

      const clampHour = (hour) =>
        Math.max(
          0,
          Math.min(24, Number(hour))
        );

      const hourX = (hour) =>
        tx(
          66 +
          (clampHour(hour) / 24) *
            (454 - 66)
        );

      for (const event of day.events) {
        const start = new Date(event.start);
        const end = new Date(event.end);

        const startHour =
          start.getUTCHours() +
          start.getUTCMinutes() / 60;

        const endHour =
          end.getUTCDate() !== start.getUTCDate()
            ? 24
            : end.getUTCHours() +
              end.getUTCMinutes() / 60;

        const row = rows[event.type] || 247;

        doc
          .moveTo(hourX(startHour), ty(row))
          .lineTo(hourX(endHour), ty(row))
          .lineWidth(1.4)
          .stroke();
      }

      doc.fontSize(6.5);

      doc.text(
        `Route: ${Number(trip.distance_miles).toFixed(1)} mi`,
        tx(66),
        ty(274)
      );

      doc.text(
        `Day driving: ${day.driving_hours.toFixed(1)} hr`,
        tx(66),
        ty(286)
      );

      doc.text(
        `Day on duty: ${day.on_duty_hours.toFixed(1)} hr`,
        tx(66),
        ty(298)
      );

      doc.text(
        "Generated by ELD Trip Planner — planned schedule, not certified ELD data",
        tx(66),
        ty(310)
      );
    });

    doc.end();
  });
}

export { createEldPdf };